### ISSUE TITLE
come accross a “OSError: [Errno 13] Permission denied”

### ISSUE THREAD

**Issue by wuk0n9** [matrix1001/heapinspect#2]
Hi，matrix1001. I try to use heapinspect to practice pwn.
when I try to use it in pwndocker,I get “OSError: [Errno 13] Permission denied”.
url of pwndocker:
```
https://github.com/skysider/pwndocker
```
How I run the docker：
```
docker run -it --rm -v /root:/ctf/work --cap-add=SYS_PTRACE skysider/pwndocker 
```
and the error info:
```
root@c83c5dbb35eb:/ctf/work# python HeapInspect.py 48                                                    
Traceback (most recent call last):                                                                      
  File "HeapInspect.py", line 34, in <module>                                                            
    hi = HeapInspector(pid)                                                                              
  File "/ctf/work/heapinspect/core.py", line 93, in __init__                                             
    libc_info = get_libc_info(self.libc_path)                                                             
  File "/ctf/work/heapinspect/libc.py", line 133, in get_libc_info                                        
    info.update(get_arena_info(libc_path, size_t))                                                        
  File "/ctf/work/heapinspect/libc.py", line 79, in get_arena_info                                        
    result = subprocess.check_output(command.split())                                                     
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output                                    
    process = Popen(stdout=PIPE, *popenargs, **kwargs)                                                    
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__                                         
    errread, errwrite)                                                                                    
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child                                  
    raise child_exception                                                                                 
OSError: [Errno 13] Permission denied            
```
would you please tell me how to solve this problem? 
thanks a lot : )

**Comment by matrix1001** [comment]
This problem should be fixed already.
You can simply use `chmod 755` for those binaries in `heapinspect\libs\*` to fix that. Try to find out if there is a permission problem.
I will check it later.

**Comment by matrix1001** [comment]
@wuk0n9 Still have that problem? Use `git pull` and try again.
