### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by ghost** [matrix1001/heapinspect#4]
使用Heapinspect.py刚开始不会有错误，但是运行一段时间之后，随着操作的增加，会在某一个固定操作之后，报如下错误。

Traceback (most recent call last):
  File "HeapInspect.py", line 55, in <module>
    pp = PrettyPrinter(hi)
  File "/home/leo/Desktop/CTF/heapinspect/heapinspect/layout.py", line 176, in __init__
    self.record = hi.record
  File "/home/leo/Desktop/CTF/heapinspect/heapinspect/core.py", line 310, in record
    return HeapRecord(self)
  File "/home/leo/Desktop/CTF/heapinspect/heapinspect/core.py", line 336, in __init__
    self.unsortedbins = hi.unsortedbins
  File "/home/leo/Desktop/CTF/heapinspect/heapinspect/core.py", line 253, in unsortedbins
    result = self.bins(0, 1)
  File "/home/leo/Desktop/CTF/heapinspect/heapinspect/core.py", line 283, in bins
    self.proc.read(chunk_ptr, chunk_size),
  File "/home/leo/Desktop/CTF/heapinspect/heapinspect/proc.py", line 296, in read
    f.seek(addr)
OverflowError: Python int too large to convert to C long

**Comment by matrix1001** [comment]
可以检查输出一下addr的内容，这个可能是和程序有关，堆块的size被篡改，就可能会造成这个错误
